# Generated by Django 3.2.5 on 2021-08-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
                ('event_agenda', models.CharField(max_length=20)),
                ('event_duration', models.DateTimeField()),
                ('event_planner_or_organiser', models.CharField(default='Samantha', max_length=20)),
                ('event_venue', models.CharField(help_text='eg Bool', max_length=20)),
                ('number_of_attendees', models.PositiveSmallIntegerField()),
                ('event_activity', models.CharField(default='Cultural day', max_length=20)),
                ('signed_by', models.CharField(default='Samantha', max_length=20)),
                ('start_time', models.DateTimeField(default='2021-07-04 00:00')),
                ('end_time', models.DateTimeField(default='2021-07-04 00:00')),
            ],
        ),
    ]
