# Generated by Django 3.2.5 on 2021-09-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_venue',
            field=models.CharField(help_text=' Bool', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_of_attendees',
            field=models.PositiveSmallIntegerField(default=200),
        ),
    ]
