# Generated by Django 3.2.5 on 2021-08-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_course', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=20)),
                ('syllabus', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('course_unit', models.CharField(max_length=15)),
                ('course_duration', models.CharField(max_length=3)),
                ('course_material', models.CharField(max_length=18)),
            ],
        ),
    ]
