# Generated by Django 3.2.5 on 2021-08-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(default=30, max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=20)),
                ('trainers_id', models.CharField(max_length=10)),
                ('no_of_lessons_attended', models.PositiveSmallIntegerField(default=1)),
                ('bank_account', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('profile_trainer', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=15)),
                ('image', models.ImageField(default='img.jpeg', upload_to='')),
                ('cv', models.FileField(default='file.pdf', upload_to='')),
            ],
        ),
    ]
