# Generated by Django 3.2.5 on 2021-08-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Nowamani', max_length=10)),
                ('last_name', models.CharField(default='Rue', max_length=10)),
                ('age', models.PositiveSmallIntegerField(default=29)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(default=867, max_length=9)),
                ('email', models.EmailField(default='anyijanet@gmail.com', max_length=254)),
                ('registration', models.PositiveIntegerField(default=1324)),
                ('phone_number', models.PositiveIntegerField(default=283957)),
                ('guardian_name', models.CharField(blank=True, default='Muhammed', max_length=15, null=True)),
                ('guardian_contacts', models.PositiveIntegerField(default=3245)),
                ('country', models.CharField(blank=True, default=40, max_length=20, null=True)),
                ('medical_report', models.FileField(blank=True, default='default.png', null=True, upload_to='')),
                ('class_name', models.CharField(blank=True, default=30, max_length=12, null=True)),
                ('room_number', models.CharField(blank=True, default=60, max_length=15, null=True)),
                ('big_sister', models.CharField(default=40, max_length=20)),
                ('mentors_name', models.CharField(blank=True, default=50, max_length=35, null=True)),
                ('passport_photo', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='')),
                ('profile', models.ImageField(default='default.jpng', upload_to='')),
            ],
        ),
    ]
